services:
  postgres:
    container_name: setuphub-db
    image: postgres:17
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME:-setuphub-db}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
